use orders;
# ANSWER TO QUESTION NUMBER 7

SELECT CARTON_ID,(LEN*WIDTH*HEIGHT) AS CARTON_VOL FROM CARTON
WHERE (LEN*WIDTH*HEIGHT) >= (SELECT (LEN*WIDTH*HEIGHT*OI.PRODUCT_QUANTITY) AS VOAI
FROM ORDER_ITEMS OI 
INNER JOIN PRODUCT P ON P.PRODUCT_ID = OI.PRODUCT_ID
WHERE OI.ORDER_ID = 10006
ORDER BY VOAI DESC
LIMIT 1)
ORDER BY CARTON_VOL
LIMIT 1;
---------------------------
# ANSWER TO QUESTION NUMBER 8

SELECT OC.CUSTOMER_ID, CONCAT(OC.CUSTOMER_FNAME," ",OC.CUSTOMER_LNAME) AS FULL_NAME,OH.ORDER_ID,SUM(OI.PRODUCT_QUANTITY) as PRODUCT_QUANTITY
FROM ONLINE_CUSTOMER OC 
INNER JOIN ORDER_HEADER OH ON OH.CUSTOMER_ID = OC.CUSTOMER_ID 
INNER JOIN ORDER_ITEMS OI ON OH.ORDER_ID = OI.ORDER_ID
WHERE OH.ORDER_STATUS = "Shipped"
GROUP BY ORDER_ID
HAVING SUM(OI.PRODUCT_QUANTITY) > 10;

-----------------
# ANSWER TO QUESTION NUMBER 9
SELECT OH.ORDER_ID,OC.CUSTOMER_ID,CONCAT(OC.CUSTOMER_FNAME," ",OC.CUSTOMER_LNAME) AS FULL_NAME,SUM(OI.PRODUCT_QUANTITY) AS PRODUCT_QUANTITY
FROM ONLINE_CUSTOMER OC 
INNER JOIN ORDER_HEADER OH ON OH.CUSTOMER_ID = OC.CUSTOMER_ID 
INNER JOIN ORDER_ITEMS OI ON OH.ORDER_ID = OI.ORDER_ID
WHERE OI.ORDER_ID > 10060 AND OH.ORDER_STATUS = "Shipped"
GROUP BY OI.ORDER_ID;

----------------------------------
# ANSWER TO QUESTION NUMBER 10

SELECT PC.PRODUCT_CLASS_DESC, SUM(OI.PRODUCT_QUANTITY) AS TOTAL_QUANTITY,(P.PRODUCT_PRICE * OI.PRODUCT_QUANTITY) AS TOTAL_VALUE
FROM ONLINE_CUSTOMER OC
INNER JOIN ORDER_HEADER OH ON OH.CUSTOMER_ID = OC.CUSTOMER_ID 
INNER JOIN ORDER_ITEMS OI ON OH.ORDER_ID = OI.ORDER_ID
INNER JOIN ADDRESS A ON A.ADDRESS_ID = OC.ADDRESS_ID
INNER JOIN PRODUCT P ON OI.PRODUCT_ID = P.PRODUCT_ID
INNER JOIN PRODUCT_CLASS PC ON  PC.PRODUCT_CLASS_CODE = P.PRODUCT_CLASS_CODE
WHERE A.COUNTRY NOT IN ("India","USA")
GROUP BY PC.PRODUCT_CLASS_DESC
ORDER BY SUM(OI.PRODUCT_QUANTITY) DESC
LIMIT 1;